name: main_workflow
on: 
  push:
    branches:
      -nodejs_linter_job
      -nodejs_jest_job

jobs:
  jobLinter:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code
        uses: github/super-linter@v3
        env: 
          DEFAULT_BRANCH: githubActions_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true